name: Deploy
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm ci
          npm run build
      - run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git add dist -f
          git commit -m "Deploy"
          git push origin HEAD:gh-pages -f