name: Deploy
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Build
        run: |
          npm ci
          npm run build

      - name: Deploy
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -f .next
          git commit -m "Deploy website"
          git push origin HEAD:gh-pages -f